server:
  port: 8777
spring:
  application:
    name: spring-sql-reactive
#  r2dbc:
#    url: r2dbc:sqlserver://localhost:1433;databaseName=microkuber;encrypt=true;trustServerCertificate=true;
#    username: sa
#    password: dcinternet
#    
  r2dbc:
      url: r2dbc:sqlserver://localhost:1433
      username: sa
      password: dcinternet
      name: microkuber  
